stages:
#- tests
- build
#- publish


variables:
  SRC_PATH: /src/github.com/StackVista/stackstate-process-agent
  STS_REPO_BRANCH_NAME: $CI_COMMIT_REF_NAME
  BASH_ENV: /root/.bashrc

build:
  image: stackstate/stackstate-agent-runner-circle:latest
  stage: build
  before_script:
    - mkdir -p /go/src/github.com/StackVista
    - ln -s $CI_PROJECT_DIR  /go/src/github.com/StackVista/stackstate-process-agent
    - curl -sL -o /usr/local/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
    - chmod +x /usr/local/bin/gimme
    - gimme 1.10.3
    - source ~/.gimme/envs/go1.10.3.env
  script:
    - apt-get install -q -y ca-certificates
    - touch $BASH_ENV
    - echo 'export IMPORT_PATH=$GOPATH/src/github.com/StackVista/stackstate-process-agent' >> $BASH_ENV
    - git status -s
    - echo "export PROCESS_AGENT_VERSION=$(packaging/version.sh)" >> $BASH_ENV
    - echo "export EBPF=${EBPF:-true}" >> $BASH_ENV
    - echo 'export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH' >> $BASH_ENV && source $BASH_ENV
    - uname -a
#    - apt-get update && apt-get -y install linux-headers-$(uname -r) rsync rake
    - apt-get update && apt-get -y install rsync rake
    - rsync -azC --delete ./ $IMPORT_PATH
    - curl https://glide.sh/get | sh
    - go get golang.org/x/tools/cmd/gorename
    - go get golang.org/x/tools/cmd/eg
    - go get golang.org/x/lint/golint
    - printenv
    - go version
    - cd $IMPORT_PATH && rake ci
    - cd packaging && ./apply_branding.sh
    - cd $IMPORT_PATH && rake build

#  tags:
#  - sts-aws
